---
- name: '[ Fedora ] Install Vim'
  dnf: 
    name: 'vim'
  become: yes

- name: 'Clone Vundle Vim package manager'
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'

- name: 'Copy .vimrc file to home directory'
  ansible.builtin.copy:
    src: '.vimrc'
    dest: '~/'
    mode: '0644'

- name: 'Copy .vim directory to home directory'
  ansible.builtin.copy:
    src: '.vim'
    dest: '~/'
    mode: '0644'
