---
- name: '[ oh-my-zsh Installation ] Check if system is RHEL8'
  stat:
    path: '/etc/redhat-release'
  register: 'stat_result'

- name: 'Check If Oh-My-Zsh Is Installed'
  stat:
    path: '/$HOME/.oh-my-zsh'
  register: 'zsh_dir'

- name: ' [ Ubuntu ] Install Oh-My-Zsh If It Does Not Exist'
  shell: 'sudo apt install zsh'
  when: not stat_result.stat.exists

- name: ' [ RHEL8 ] Install Oh-My-Zsh If It Does Not Exist'
  shell: 'sudo yum install zsh'
  when: stat_result.stat.exists

- name: 'Copy .zshrc file to home directory'
  ansible.builtin.copy:
    src: '.zshrc'
    dest: '~/'

- name: 'Copy .zsh_aliases file to home directory'
  ansible.builtin.copy:
    src: '.zsh_aliases'
    dest: '~/'

- name: 'Apply oh-my-zsh configurations'
  shell: 'source ~/.zshrc'
  args:
     executable: '/bin/bash'