name: Test Ubuntu Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-login:
    name: Login to Docker Hub
    uses: actions/checkout@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      
  docker-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker pull ubuntu:20.04
      
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
